# Generated by Django 3.0.5 on 2022-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20221212_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
